name: Nix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  build:
    name: Build with Nix
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # v31.8.4
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build package
        run: nix build

      - name: Check flake
        run: nix flake check

      - name: Build devShell
        run: nix develop --command echo "Dev shell works"
